### PR TITLE
5. Add admin static files on production

### PR DESCRIPTION
**Pull request by libdx**
Configure Nginx to server staticfiles

### CODE REVIEW

**Comment by libdx** [comment]
it's a result of running 
```sh
$ python manage.py collectstatic
```
From the docs:
>Deployment
>
>django.contrib.staticfiles provides a convenience management command for gathering static files in a single directory so you can serve them easily.
>
>    Set the STATIC_ROOT setting to the directory from which you’d like to serve these files, for example:
>
>    STATIC_ROOT = "/var/www/example.com/static/"
>
>    Run the collectstatic management command:
>
>    $ python manage.py collectstatic
>
>    This will copy all files from your static folders into the STATIC_ROOT directory.
>
>    Use a web server of your choice to serve the files. Deploying static files covers some common deployment strategies for static files.

**Comment by pioole** [comment]
From:
https://stackoverflow.com/questions/41558258/should-i-add-django-admin-static-files-to-my-git-repo/41558803

> While you can absolutely check these files in, I typically recommend not checking in the collected static files into git (we use .gitignore to ignore them). Instead, we call collectstatic during our build/deploy steps so that if anyone ever adds new static files, they are collected and copied to the proper output directory for serving by nginx or sent up to s3. If you want to check them into git, I would recommend having collectstatic as a precommit hook so that no one accidentally forgets to run it when adding a new static file.

Choose either path then. Personally I would go for removing these files from repository.

**Comment by libdx** [comment]
Ok, I'll add command for generating static files as a part of Docker file for production.

**Comment by libdx** [comment]
As we have agreed, for now I'll leave static files as is, to not spend extra time on configuration of build/deploy steps.

**Comment by pioole** [comment]
Yup +1

**Pull request merged**
